# Generated by Django 6.0.2 on 2026-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_files',
            field=models.FileField(blank=True, help_text='Upload any additional files (ZIP, DOCX, etc.)', null=True, upload_to='projects/additional/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload project documentation, report, or presentation', null=True, upload_to='projects/documents/'),
        ),
    ]
