# Generated by Django 6.0.2 on 2026-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_additional_files_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
